server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/app
    username: app
    password: app
  flyway:
    url: jdbc:postgresql://postgres:5432/app
    user: app
    password: app

app:
  googleSheets:
    generalBaseUrl: https://script.google.com/macros/s/GENERAL/exec
    disBaseUrl: https://script.google.com/macros/s/PUNISHMENT/exec
