server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/app
    username: app
    password: app
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/app
    user: app
    password: app
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG

app:
  googleSheets:
    generalBaseUrl: https://script.google.com/macros/s/AKfycbzNPh2GqaYwO8jlcPYPHz9zOXiS1rFM3V62HiF5xnex_Yynp_3ktWZChzFLWHviVa7u/exec
    disBaseUrl: https://script.google.com/macros/s/AKfycbzBrD3lRWL7upwq6gKO95BTtlLmkSij-B383E42oaLd2ydDG61KHnmuP0yTatQSO2BOLw/exec
